name: CI

on:
  push:
    branches: ["develop"]
  pull_request: {}
  workflow_dispatch: {}

permissions:
  actions: read
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/setup-rust
      - name: Rust Build
        run: cargo build --all-features --all-targets
      - name: Rust Lint - Format
        run: cargo fmt --all --check
      - name: Rust Lint - Clippy
        run: cargo clippy --all-features --all-targets
      - name: Rust Test
        run: cargo test --workspace --all-features

  msrv:
    name: MSRV Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Get MSRV
        id: msrv
        run: echo "version=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[0].rust_version')" >> $GITHUB_OUTPUT
      - name: Install MSRV Toolchain
        uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # master
        with:
          toolchain: "${{ steps.msrv.outputs.version }}"
      - name: Rust Build
        run: cargo build --all-features --all-targets

  bench-codspeed:
    name: Benchmark with Codspeed
    runs-on:
      - runs-on=${{ github.run_id }}
      - family=c6id.8xlarge
      - image=ubuntu24-full-x64
      - tag=bench-codspeed
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/setup-rust

      - name: Install Codspeed
        shell: bash
        run: cargo install --force cargo-codspeed --locked

      - name: Build benchmarks
        env:
          RUSTFLAGS: "-C target-feature=+avx2"
        run: |
          cargo codspeed build --profile bench -m instrumentation

      - name: Run benchmarks - Instrumentation
        uses: CodSpeedHQ/action@f22792bfac16f3e14eb9fbea76f4a48e9cc22b93 # v4
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
          mode: instrumentation
