name: Publish

concurrency:
  group: publish
  cancel-in-progress: true

on:
  release:
    types: [published]

jobs:
  publish-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/setup-rust
      - name: Install cargo-edit
        uses: taiki-e/cache-cargo-install-action@7824a3d828d84688fd069e57300b218c7b81eefa
        with:
          tool: cargo-edit

      - name: Cargo Set Version
        run: |
          cargo set-version ${{ github.event.release.tag_name }}
      - name: Release
        run: cargo publish --allow-dirty
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
